project:
  type: book
  output-dir: docs

book:
  title: "Skinny Physics for QS&BB"
  author: "Chip Brock"
  date: "2025-09-12"
  chapters:
    - index.qmd
    - intro.qmd
    - part: mechanics/index.qmd
      chapters:
        - mechanics/motion/motion.qmd
        - mechanics/momentum/momentum.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    fontsize: 1.3em
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
